project:
  type: website

website:
  title: "Jinho Kim"
  description: "Technical posts on image processing, neuro data analysis, and machine learning"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/jkim0731/
        aria-label: GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/jinho-kim-548a447/
        aria-label: LinkedIn
      - icon: twitter-x
        href: https://x.com/jkimkj
        aria-label: X (Twitter)
      - icon: mortarboard-fill
        href: https://scholar.google.com/citations?user=IcxEW8YAAAAJ&hl=en
        aria-label: Google Scholar

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    grid:
      body-width: 850px
