project:
  type: website

website:
  title: "Jinho Kim"
  description: "Computational imaging & imaging ML portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: blog.qmd
        text: Blog
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://www.linkedin.com/

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    grid:
      body-width: 850px
